config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root 'pages#home'
   get 'about', to: 'pages#about'
   resources :articles
   get 'signup', to: 'users#new'
   resources :users, except: [:new]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  has_rich_text :description
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #before we do any actions, call the set_article method, but only for the show, edit, update, and destroy methods
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    
  end

  #Method to display all the articles
  def index
    #display all the articles
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  #Method to create new articles
  def new
    #create an instance variable to hold a new article item formed after out Article table
    @article = Article.new
  end

  #Method to edit existing articles
  def edit

  end

  #Method to create a new article from input inside our form 
  def create
    #Call method to whitelist params for the article
    @article = Article.new(article_params)
    #Hard coding in a user_id to the new article
    @article.user = current_user
    #save the new article to the table
    if @article.save
      #if doing the above action was successful - returns true - then do the next items
      #set flash 'notice' to the following message
      flash[:success] = "Article was created sucessfully."
      #redirect to the new article page
      redirect_to @article
    else
      #if doing the above action wasn't successful - returns false - then do the next items
      #render/ display an updated 'new' template, because this 'create' action is on the 'new.html.erb' page
      render 'new'
    end  
  end

  #Method to update an existing article that we edited in a table
  def update
    #Call method to whitelist params for the article
    if @article.update(article_params)
      #if doing the above action was successful - returns true - then do the next items
      #update the flash helper hash's 'notice'
      flash[:success] = "Article was updated successfully."
      #redirect from the current update page to the articles page
      redirect_to @article
    else
      #if doing the above action wasn't successful - returns false - then do the next items
      #render/ display an updated 'edit' template, because this 'update' action is on the 'edit.html.erb' page
      render 'edit'
    end

  end

  def destroy
    @article.destroy
    flash[:success] = "Article was successfully deleted."
    redirect_to articles_path
  end

  #Makes anything below this line only available to this file
  private

  #Private Method that sets the article by finding the id of that article from the url paramater
  def set_article
    #set a specific article by the id value to the instance @article
    @article = Article.find(params[:id])
  end

  #Private method that finds the parameters for our article
  def article_params
    #whitelists the parameters of an article
    params.require(:article).permit(:title, :subtitle, :description, :public, :private, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own article"
      redirect_to root_path
    end
  end

end

app/views/articles/_article.html.erb
<div class="container">
  
  <% @articles.each do |article| %>
    <% if article.public || (!article.public && !article.private) || (article.private && current_user == article.user) %>
      <div class="row justify-content-center">
        <div class="col-8 mb-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <% if article.user %>
                  By: <%= link_to article.user.username, user_path(article.user) %>
              <% end %>
              <% if article.private %>
                <br><small>private article - viewable only by you</small>
              <% end %>
              <% if !article.public && !article.private%>
                <br><small>member only article</small>
              <% end %>
              <% if article.public && logged_in?%>
                <br><small>public article</small>
              <% end %>
            </div>
            <div class="row justify-content-center">
              <% if !article.public && !logged_in? %>
                <div class="card-body col-10">
                  <h5 class="card-title mb-0">
                      <%= article.title%>
                  </h5>
                  <div class="card-text m-0 p-0">
                    <%= link_to "Sign In to view article content", login_path %></div>
                  <% if article.categories.any? %>
                    <p class="text-muted"><small>Categories: <%= render article.categories %></small></p>
                  <% end %>
                  <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                  <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-primary" %>
                    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                  <% end %>
                </div>
              <% else %>
                <div class="card-body col-10">
                  <h5 class="card-title mb-0">
                      <%= link_to article.title, article_path(article), class: "text-success" %>
                  </h5>
                  <div class="card-text m-0 p-0">
                    <%= simple_format(truncate(article.description.to_s, 
                                                                      :length => 180, 
                                                                      :separator => " ", 
                                                                      :escape => false)) %></div>
                  <% if article.categories.any? %>
                    <p class="text-muted"><small>Categories: <%= render article.categories %></small></p>
                  <% end %>
                  <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                  <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-primary" %>
                    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(article.created_at) %> ago,
              edited <%= time_ago_in_words(article.updated_at) %> ago </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/articles/_form.html.erb
<div class="container">

  <div class="row justify-content-center">

    <div class="col-10">

      <%= render 'shared/errors', obj: @article %>

      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>

        <div class="form-group row">

          <%= f.label :title, class: "col-2 col-form-label text-light" %>

          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Article" %>
          </div>

        </div>

        <div class="form-group row">

          <%= f.label :subtitle, class: "col-2 col-form-label text-light" %>

          <div class="col-10">
            <%= f.text_field :subtitle, class: "form-control shadow rounded", placeholder: "Subtitle of Article" %>
          </div>

        </div>

        <div class="form-group row">

          <%= f.label :description, class: "col-2 col-form-label text-light" %>

          <div class="col-10">
            <%= f.rich_text_area :description, class: "form-control shadow rounded", placeholder: "Description of Article" %>
          </div>

        </div>

        <div class="form-group row">
          <div class="col-2"></div>

          <div class="col-10">
            <%= f.check_box :public, class: "checkbox mr-1" %>
            <%= f.label :public, class: "checkbox-inline input_checkbox mr-1" %><small>(viewable without login)</small>
            <%= f.check_box :private, class: "checkbox ml-2 mr-1" %>
            <%= f.label :private, class: "checkbox-inline input_checkbox mr-1" %><small>(viewable only by you)</small>
          </div>

        </div>

        <div class="form-group row">
          <div class="col-2"></div>

          <div class="col-10">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox mr-4") {cb.check_box(class: "checkbox mr-2") + cb.text } %>
            <% end %>
          </div>

        </div>

        <div class="form-group row justify-content-center">

          <%= f.submit class: "btn btn-outline-light btn-lg" %>

        </div>

      <% end %>

    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and Return to Articles Listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
  
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 mb-4" >Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4" >Articles Listing</h1>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 mb-4" >Create New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container article-show bg-light border p-0">

  <div class="article-header card-header mb-4">
    <div class="row justify-content-center article-date">
      <small class="text-muted"><%= @article.created_at.to_date %></small>
    </div>
    <div class="row justify-content-center article-title">
      <h1><%= @article.title %></h1>
    </div>
    <% if @article.subtitle.present? %>
      <div class="row justify-content-center article-subtitle">
        <h4><%= @article.subtitle.downcase %></h4>
      </div>
    <% end %>
  </div>

  <div class="article-body mt-4 mb-4">
    <div class="row p-4 justify-content-center article-content">
      <div class="col-10">
        <%= @article.description %>
      </div>
    </div>
  </div>

  <div class="article-footer card-footer mt-4 text-muted">
    <div class="row justify-content-center">
      <div class="article-edited">
        <small><em>Edited <%= time_ago_in_words(@article.updated_at) %> ago</em></small></br>
        <% if current_user == @article.user %>
          <div class="row justify-content-center">
            <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-sm btn-outline-primary' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row pt-2 pr-4 pb-4 pl-4">
      <div class="user-image pl-2">
        <% if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <% end %>
      </div>
      <div class="col-6">
        <div class="article-author pt-0 pb-1">
          <% if @article.user %>
            <small><strong>Article by <%= link_to @article.user.username, user_path(@article.user) %></strong></small>
          <% end %>
        </div>
        <% if @article.user.info.present? %>
          <div class="author-about">
            <small><%= @article.user.info %></small>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>