config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root 'pages#home'
   get 'about', to: 'pages#about'
   resources :articles
   get 'signup', to: 'users#new'
   resources :users, except: [:new]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:edit, :update, :show]

  def index
    #display all the articles
    @categories = Category.paginate(page: params[:page], per_page: 5)
    
  end

  def new
    @category = Category.new

  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end

  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category name was successfully update"
      redirect_to category_path(@category)
    else
      render 'edit'
    end

  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end

  end

end

app/views/categories/_category.html.erb
<span><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<div class="container">

  <div class="row justify-content-center">

    <div class="col-10">

      <%= render 'shared/errors', obj: @category %>

      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>

        <div class="form-group row">

          <%= f.label :name, class: "col-2 col-form-label text-light" %>

          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a Category Name" %>
          </div>

        </div>

        <div class="form-group row justify-content-center">

          <%= f.submit class: "btn btn-outline-light btn-lg" %>

        </div>

      <% end %>

    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and Return to Category Listing ]', categories_path, class: "text-info" %>
    </div>
  </div>
  
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 mb-4" >Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4" >Category Listing</h1>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
      <div class="col-4">
        <div class="card card-body text-center shadow mb-5 bg-white rounded">
          <h2><%= link_to category.name, category_path(category) %></h2>
          <p class="text-muted m-0"><small><%= pluralize(category.articles.count, "Article") %></small></p>
        </div>
      </div>
    </div>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 mb-4" >Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h2 class="text-center mt-4 mb-4" ><%= "Category: " + @category.name %></h2>

<div class="row justify-content-center">
  <% if logged_in? and current_user.admin? %>
    <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-outline-primary" %>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @category_articles, :container => false %>
</div>

<% @category_articles.each do |article| %>
  <div class="row justify-content-md-center">
      <div class="col-6">
        <div class="card card-body text-center shadow mb-5 bg-white rounded">
          <h2><%= link_to article.title, article_path(article) %></h2>
        </div>
      </div>
    </div>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @category_articles, :container => false %>
</div>